package it.polimi.ingsw.am37.message;

/**
 * General confirm message. Used by server when no other more specific replays are suitable to choose that requested
 * action have been performed successfully. This message should not been used when errors have been generated by
 * previous actions.
 */
public class ConfirmMessage extends Message {

    /**
     * The fromJSON receiver side constructor where all data are accessible
     *
     * @param UUID the sender identifier
     */
    public ConfirmMessage(String UUID) {
        super(UUID, MessageType.CONFIRM);
    }

    /**
     * The default constructor for message preparing. UUID must be set using {@link Message#setUUID(String)} before
     * sending it
     *
     * @param messageType the message enum type
     */
    public ConfirmMessage(MessageType messageType) {
        super(messageType);
    }
}
